/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.SistemaColeccionUnidades;
import modelo.clases.*;
import modelo.Unidad;
import utilidades.Utilidades;

/**
 *
 * @author elthe
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private SistemaColeccionUnidades coleccion = new SistemaColeccionUnidades();
    // Variable que guardará la unidad temporalmente
    private Unidad unidadTemp; 
    
    public VentanaPrincipal() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCrear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbClaseCrear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCrearClase = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNivelCrear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtExpCrear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPvCrear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFueCrear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHabCrear = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVelCrear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSueCrear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDefCrear = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtResCrear = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Clase:");

        cbClaseCrear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(- Selecciona la clase -)", "Mirmidon", "Guerrero" }));
        cbClaseCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClaseCrearActionPerformed(evt);
            }
        });

        tbCrearClase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nivel", "Experiencia", "Clase", "Descripción", "PV", "Fuerza", "Habilidad", "Velocidad", "Suerte", "Defensa", "Resistencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCrearClase);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel3.setText("Nivel:");

        txtNivelCrear.setText("1");

        jLabel4.setText("Experiencia:");

        txtExpCrear.setText("0");

        jLabel5.setText("Crecimientos:");

        jLabel6.setText("PV:");

        txtPvCrear.setText("0");

        jLabel7.setText("Fuerza:");

        txtFueCrear.setText("0");
        txtFueCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFueCrearActionPerformed(evt);
            }
        });

        jLabel8.setText("Habilidad:");

        txtHabCrear.setText("0");

        jLabel9.setText("Velocidad:");

        txtVelCrear.setText("0");

        jLabel10.setText("Suerte:");

        txtSueCrear.setText("0");

        jLabel11.setText("Defensa:");

        txtDefCrear.setText("0");

        jLabel12.setText("Resistencia:");

        txtResCrear.setText("0");

        jLabel13.setText("Un nivel sobre 1 provocara que la unidad suba de nivel");

        jLabel14.setText("aumentando sus estadisticas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNivelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExpCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbClaseCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPvCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDefCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtResCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(txtFueCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHabCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSueCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCrear))))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNivelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtExpCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbClaseCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrear))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPvCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtHabCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtSueCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFueCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDefCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtResCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtVelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Unidad", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Buscar Unidad", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
    // Verifica si la unidad ha sido creada
    if (unidadTemp != null) {
        // Agrega la unidad al ArrayList
        coleccion.agregarUnidad(unidadTemp);

        // Opcionalmente, muestra un mensaje indicando que se ha creado la unidad
        javax.swing.JOptionPane.showMessageDialog(this, "Unidad creada exitosamente.");

        // Limpiar la variable temporal para permitir una nueva creación si es necesario
        unidadTemp = null;
    } else {
        // Si no hay ninguna unidad temporal, muestra un mensaje de advertencia
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una clase y completar los campos antes de crear la unidad.");
    }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cbClaseCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClaseCrearActionPerformed
        // Obtén la clase seleccionada del combo box
        String clase = cbClaseCrear.getSelectedItem().toString();

        // Valida si el usuario seleccionó una clase
        if (cbClaseCrear.getSelectedIndex() == 0) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una clase válida.");
            return;
        }

        // Crea una nueva unidad
        Unidad uni = new Unidad();

        // Obtén los valores de los campos
        String nombre = txtNombreCrear.getText().trim();
        String nivel = txtNivelCrear.getText().trim();
        String experiencia = txtExpCrear.getText().trim();
        String pv = txtPvCrear.getText().trim();
        String fue = txtFueCrear.getText().trim();
        String hab = txtHabCrear.getText().trim();
        String vel = txtVelCrear.getText().trim();
        String sue = txtSueCrear.getText().trim();
        String def = txtDefCrear.getText().trim();
        String res = txtResCrear.getText().trim();

        // Valida que todos los campos estén llenos
        if (nombre.isBlank() || nivel.isBlank() || experiencia.isBlank() || pv.isBlank() ||
                fue.isBlank() || hab.isBlank() || vel.isBlank() || vel.isBlank() || sue.isBlank() ||
                def.isBlank() || res.isBlank()) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes llenar todos los campos.");
            cbClaseCrear.setSelectedIndex(0);
            return;
        }

        // Convierte los valores de nivel y experiencia a enteros, con manejo de errores
        int cantNivel;
        int cantExp;
        int cantPv, cantFue, cantHab, cantVel, cantSue, cantDef, cantRes;

        try 
        {
            cantNivel = Integer.parseInt(nivel);
            cantExp = Integer.parseInt(experiencia);
            cantPv = Integer.parseInt(pv);
            cantFue = Integer.parseInt(fue);
            cantHab = Integer.parseInt(hab);
            cantVel = Integer.parseInt(vel);
            cantSue = Integer.parseInt(sue);
            cantDef = Integer.parseInt(def);
            cantRes = Integer.parseInt(res);
        } 
        catch (NumberFormatException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Los valores deben ser números enteros.");
            return;
        }

        // Valida los rangos de nivel y experiencia
        if (!Utilidades.validarRango(this, cantNivel, 1, 20, "El nivel debe estar entre 1 y 20")) 
        {
            cbClaseCrear.setSelectedIndex(0);
            return;
        }

        if (!Utilidades.validarRango(this, cantExp, 0, 99, "La experiencia debe estar entre 0 y 99")) 
        {
            cbClaseCrear.setSelectedIndex(0);
            return;
        }

        // Intenta asignar la clase seleccionada a la unidad usando ClaseFactory
        try 
        {
            uni.setClase(ClaseFactory.crearClase(clase));
        } 
        catch (IllegalArgumentException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        }

        // Asigna el nombre, nivel y experiencia a la unidad
        uni.setNombre(nombre);
        uni.getClase().getNivel().setNivel(cantNivel);
        uni.getClase().getNivel().setExperiencia(cantExp);
        
        // Asigna los crecimientos a la unidad
        uni.getClase().getCrecimiento().setCrePv(cantPv);
        uni.getClase().getCrecimiento().setCreFue(cantFue);
        uni.getClase().getCrecimiento().setCreHab(cantHab);
        uni.getClase().getCrecimiento().setCreVel(cantVel);
        uni.getClase().getCrecimiento().setCreSue(cantSue);
        uni.getClase().getCrecimiento().setCreDef(cantDef);
        uni.getClase().getCrecimiento().setCreRes(cantRes);
        
        // Subir las estadísticas de acuerdo con el nivel actual.
        int nivelActual = uni.getClase().getNivel().getNivel();
        if (nivelActual > 1) 
        {
            System.out.println(uni.getNombre() + " ha subido al nivel " + nivelActual);

            // Llamamos a subirNivel tantas veces como niveles tenga la unidad.
            // Se pueden hacer ajustes más avanzados si los niveles se manejan de otra forma.
            for (int i = 1; i < nivelActual; i++) {
                uni.getClase().subirNivel();
            }
        }

        // Actualiza la tabla con los datos de la unidad
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tbCrearClase.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        modelo.addRow(new Object[] 
        {
            uni.getNombre(),
            uni.getClase().getNivel().getNivel(),
            uni.getClase().getNivel().getExperiencia(),
            uni.getClase().getNombre(),
            uni.getClase().getDescripcion(),
            uni.getClase().getEstadisticas().getPv(),
            uni.getClase().getEstadisticas().getFue(),
            uni.getClase().getEstadisticas().getHab(),
            uni.getClase().getEstadisticas().getVel(),
            uni.getClase().getEstadisticas().getSue(),
            uni.getClase().getEstadisticas().getDef(),
            uni.getClase().getEstadisticas().getRes()
        });
        
        unidadTemp = uni;
    }//GEN-LAST:event_cbClaseCrearActionPerformed

    private void txtFueCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFueCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFueCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cbClaseCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbCrearClase;
    private javax.swing.JTextField txtDefCrear;
    private javax.swing.JTextField txtExpCrear;
    private javax.swing.JTextField txtFueCrear;
    private javax.swing.JTextField txtHabCrear;
    private javax.swing.JTextField txtNivelCrear;
    private javax.swing.JTextField txtNombreCrear;
    private javax.swing.JTextField txtPvCrear;
    private javax.swing.JTextField txtResCrear;
    private javax.swing.JTextField txtSueCrear;
    private javax.swing.JTextField txtVelCrear;
    // End of variables declaration//GEN-END:variables
}
